# Generated by Django 2.0.2 on 2018-02-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160801_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
